### ISSUE TITLE
The resulting style file has redundant 'border-radius' attributes

### ISSUE THREAD

**Issue by xingorg1** [mzohaibqc/antd-theme-generator#97]
**Describe the bug**
When I have a 'border-radius' attribute in my style, the 'color.less' file still has the 'border-radius' attribute unculled.

**Show your code**
theme/default.less
```css
.setting-theme {
  display: inline-block;
  font-size: 0;
  padding: 10px 10px;
  background: @background-color-light;
  margin-right: 5px;
  border-radius: 4px;
  cursor: pointer;
}
```
color.less：
```css
.setting-theme {
  background: @background-color-light;
  border-radius: 4px;  /* it‘s redundant */
}
```

**Version**
I'm using the latest version
